[tool.poetry]
name = "funda-insights"
version = "0.1.0"
description = "A project to gain insights into the housing markrt using funda."
authors = ["Mark Berger <maberger0811@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
